version: '3.5'
services:
  maplestory:
    build: .
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      LG_PORT_BASE: ${LG_PORT_BASE}
      CH_PORT_BASE: ${CH_PORT_BASE}
      WAIT_HOSTS: ${DB_DN}:3306
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8302:8302'
      - '8303:8303'
    networks:
      - internal-net
    container_name: atlas-ms
networks:
  internal-net:
    name: internal-net
